name: 'Code-Formatter'
desciption: 'Format Ruby, Terraform, YAML, Python, Markdown and JSON file within a PR'
runs:
  using: "composite"  
  steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.head_ref }}
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
    - run: | 
        npm install prettier
        pip3 install autopep8
        bundle init
        bundle add standardrb
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        base_branch_sha=$(git rev-parse --short ${GITHUB_BASE_REF})
        branch_sha=$(git rev-parse --short ${GITHUB_REF_NAME})
        echo $base_branch_sha
        echo $branch_sha
        git diff-tree -r --no-commit-id --name-only --diff-filter=ACMRT $base_branch_sha $branch_sha > modified_files.txt
        chmod 755 modified_files.txt
        while IFS= read -r line
        do
          echo "$line"
          if [[ $line == *".py"* ]]; then
            echo "It's a python file!"
            python3 -m autopep8 --in-place -r .
          elif [[ $line == *".rb"* ]]; then
            echo "It's a ruby file!"
            bundle exec standardrb --fix
          elif [[ $line == *".tf"* ]]; then
            echo "It's a terraform file!"
            terraform fmt -recursive
          elif [[ $line == *".yaml"* || $line == *".yml"* || $line == *".md"* || $line == *".json"* ]]; then
            echo "It's a yml,yaml,md,json file!"
            npx prettier --print-width=150 --write "**/*.{yml,yaml,md,json}"
          fi
        done < "$input"
        rm -rf Gemfile Gemfile.lock package-lock.json package.json node_modules namespaces modified_files.txt
        git ls-files --deleted -z | git update-index --assume-unchanged -z --stdin
        if [ -n "$(git status --porcelain=1 --untracked-files=no)" ]; then
          git add --ignore-removal .
          git commit -m "Commit changes made by code formatters"
          git push
        else
          echo "No Code Formatter changes";
        fi
      shell: bash
