name: 'Code-Formatter'
desciption: 'Format Ruby, Terraform, YAML, Python, Markdown and JSON file within a PR'
runs:
  using: "composite"  
  steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.head_ref }}
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
    - run: | 
        git branch -r
        git status
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        terraform fmt -recursive
        bundle init
        bundle add standardrb
        bundle exec standardrb --fix
        pip3 install autopep8
        python3 -m autopep8 --in-place -r .
        npm install prettier
        npx prettier --print-width=150 --write "**/*.{yml,yaml,md,json}"
        rm -rf Gemfile Gemfile.lock package-lock.json package.json node_modules namespaces
        git status
        git add --ignore-removal .
        git commit -m "Commit changes made by code formatters"
        git status
        git push
      shell: bash 
