name: 'Code-Formatter'
desciption: 'Format Ruby, Terraform, YAML, Python, Markdown and JSON file within a PR'
runs:
  using: "composite"
  env:
    BUNDLE_GEMFILE: ${{ github.workspace }}/code-formatter/Gemfile   
  steps:
    - run: terraform fmt
      shell: bash
    - uses: actions/checkout@v3
      with:
        repository: https://github.com/ministryofjustice/github-actions
        ref: new-code-formatter
        path: code-formatter     
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
    - run: bundle standardrb --fix
      shell: bash
    - run: pip3 install black && python3 -m black **/*.py
      shell: bash
    - run: npm install prettier && npx prettier --print-width=150 --write "**/*.{yml,yaml,md,json}"
      shell: bash
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Code-Formatter change/s.