name: 'Code-Formatter'
desciption: 'Format Ruby, Terraform, YAML, Python, Markdown and JSON file within a PR'
runs:
  using: "composite"  
  steps:
    - run: terraform fmt
      shell: bash
    - uses: ruby/setup-ruby@v1
    - run: ls -al
    - run: BUNDLE_GEMFILE=Gemfile bundle install && bundle standardrb --fix
      shell: bash
    - run: pip3 install black && python3 -m black **/*.py
      shell: bash
    - run: npm install prettier && npx prettier --print-width=150 --write "**/*.{yml,yaml,md,json}"
      shell: bash
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Code-Formatter change/s.