name: 'Code-Formatter'
desciption: 'Format Ruby, Terraform, YAML, Python, Markdown and JSON file within a PR'
runs:
  using: "composite"  
  steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.head_ref }}
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
    - run: | 
        npm install prettier
        pip3 install autopep8
        bundle init
        bundle add standardrb
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git fetch origin $GITHUB_BASE_REF --depth=50
        base_branch_sha=${{ github.event.pull_request.base.sha }}
        head_branch_sha=${{ github.event.pull_request.head.sha }}
        echo $base_branch_sha
        echo $head_branch_sha
        git diff-tree -r --no-commit-id --name-only --diff-filter=ACMRT $base_branch_sha $head_branch_sha > modified_files.txt
        chmod 755 modified_files.txt
        while IFS= read -r file
        do
          echo "$file"
          if [[ $file == *".py"* ]]; then
            python3 -m autopep8 --in-place $file
          elif [[ $file == *".rb"* ]]; then
            bundle exec standardrb --fix $file
          elif [[ $file == *".tf"* ]]; then
            terraform fmt $file
          elif [[ $file == *".yaml"* || $file == *".yml"* || $file == *".md"* || $file == *".json"* ]]; then
            npx prettier --print-width=150 --write $file
          fi
        done < modified_files.txt
        rm -rf Gemfile Gemfile.lock package-lock.json package.json node_modules namespaces modified_files.txt
        git ls-files --deleted -z | git update-index --assume-unchanged -z --stdin
        if [ -n "$(git status --porcelain=1 --untracked-files=no)" ]; then
          git add --ignore-removal .
          git commit -m "Commit changes made by code formatters"
          git push
        else
          echo "No Code Formatter changes";
        fi
      shell: bash
