name: "Check Version Pinning"
description: "GitHub Action to check for untrusted GitHub Actions not pinned to a SHA hash."

inputs:
  workflow_directory:
    description: "Directory to scan for GitHub workflow files."
    required: false
    default: ".github/workflows"
  scan_mode:
    description: "Mode to run the scan: 'full' (scan whole repo) or 'pr_changes' (scan only PR changes)."
    required: false
    default: "full"

outputs:
  found_unpinned_actions:
    description: "Indicates if unpinned actions were found."

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.workflow_directory }}
    - ${{ inputs.scan_mode }}
