# Need a GitHub Advanced Security license to run this action on private repos.

name: Dependency Review
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          # Possible values: critical, high, moderate, low
          fail-on-severity: critical
