on:
  workflow_dispatch:
  # pull_request:
  #   types: [opened, edited, reopened, synchronize]

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ministryofjustice/github-actions/code-formatter@${GITHUB_REF}
        with:
          workspace: ${GITHUB_WORKSPACE}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
