name: code-formatter

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: ministryofjustice/github-actions/code-formatter@v14
        with:
          ignore-files: "bad.yml,bad.yaml,secret-bad.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
