name: Python Malformed YAML
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  test-python-malformed-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.2
      - name: Detect malformed YAML files
        uses: ministryofjustice/github-actions/python-malformed-yaml@mal-yaml-to-python
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
