name: Terraform static code analysis - reuseable workflow

on:
  workflow_call:
    inputs:
      scan_type:
        description: 'full = all tf folders, changed = tf changes, single = single folder'
        required: false
        default: "single"
        type: string
      terraform_working_dir:
        description: 'define a target folder for the scan - does not include sub-folders'
        required: false
        default: '.'
        type: string
      tfsec_exclude:
        description: 'Provide checks via , without space to exclude from run'
        required: false
        type: string
      checkov_exclude:
        description: 'Provide checks via , without space to exclude from run'
        required: false
        type: string
      tflint_exclude:
        description: 'Provide checks via , without space to exclude from run'
        required: false
        type: string
      tflint_config:
        description: 'Provide a specific config for this run (including the .hcl extension), see the "tflint-configs" folder for available configs'
        required: false
        default: 'tflint.default.hcl'
        type: string

jobs:
  terraform-static-analysis-scan:
    name: Terraform static code analysis - reuseable workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # security best practice: use specific version of public actions (v0.3.0)
      - name: Hide previous PR comments
        uses: int128/hide-comment-action@5aa4ad6cf762098ebdc5d3c046e9e1fb35fe5ce8
        if: ${{ github.event_name == 'pull_request' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          authors: ""
          starts-with: "####"

      - name: Run Analysis
        uses: ministryofjustice/github-actions/terraform-static-analysis@v14
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          scan_type: ${{ inputs.scan_type }}
          tfsec_exclude: ${{ inputs.tfsec_exclude }}
          checkov_exclude: ${{ inputs.checkov_exclude }}
          terraform_working_dir: ${{ inputs.terraform_working_dir }}
          tflint_exclude: ${{ inputs.tflint_exclude }}
          tflint_config: ${{ inputs.tflint_config }}
