name: Test advisories-to-slack python filter script

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "format-github-advisories-for-slack/**"

defaults:
  run:
    working-directory: ./format-github-advisories-for-slack

jobs:
  python-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install python dependencies
        run: |
          pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
          pip install --no-cache-dir -r requirements-dev.txt

      - name: run unit tests
        id: python-tests
        run: pytest -vv tests/
